### ISSUE TITLE
maftools oncoplot result 

### ISSUE THREAD

**Issue by lkalbert001** [PoisonAlien/maftools#102]
Hi, I have a question about the oncoplot result. 
Can you tell me which types of **Variant_Classification** in MAF files included when I use oncoplot.

Or if only those **Variant_Classification** types are included, then why does oncoplot  abandon other types like Intron and so on. Does oncoplot have any methods support this trimming. 
<img width="288" alt="2018-01-11 13 27 48" src="https://user-images.githubusercontent.com/34129931/34809946-56ff5898-f6d3-11e7-8b09-8b1c1763e0c0.png">

Look forward to your reply！

**Comment by PoisonAlien** [comment]
Hello,

Only non-synonymous Variant_Classifications are used for most of the downstream analysis. Try `?read.maf` and see the argument `vc_nonSyn`. You can provide a manual list of `Variant_Classification` 
 to `vc_nonSyn` that you would like to consider as the required ones while reading your maf files and it should do the trick. For plotting you will have provide manual list of colors since oncoplot have pre-defined color code for only non-synonymous variants. [See](http://www.bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/maftools.html#523_changing_colors,_including_mutsig_q-values,_adding_annotations_and_sorting) vignette for details on how to define color codes for variant classifications.

Hope this helps.

**Comment by lkalbert001** [comment]
Got it . 
Thanks for your reply!
