### ISSUE TITLE
Question on pValue and Odds Ratio Calculation in Your Maftools Paper

### ISSUE THREAD

**Issue by dschslava** [PoisonAlien/maftools#126]
Dear PoisonAlien,

I'm a high school student doing biomedical research and am reading your paper posted on https://www.bioconductor.org/packages/3.7/bioc/vignettes/maftools/inst/doc/maftools.html#7_analysis.

I have two simple questions related to your Section 7.1.

After the somatic interaction figure, I have the following data from your paper:

##  1:  RUNX1  ASXL1 0.0001573764 54.9015813 175  4  1 12       Co_Occurance

For the last line listed above, it seems to me that
pValue = 4 / (192 * 192) = 0.000108507 which is different from your pValue of 0.0001573764. 

Could you tell me why my pValue calculation is wrong?

As to the oddsRatio, it seems to me that
oddsRatio = (175 * 4) / ( 1 * 12) = 58.3333333 which is different from your value of 54.9015813. 

Could you let me know why my oddRatio calculation is wrong?

Thanks!

**Comment by PoisonAlien** [comment]
Hello,

I am not sure whats going on, because honestly I have never calculated OR or p-values by hand. I would guess `fisher.test` in R is doing something ? But again, the differences you're seeing are marginal, so I guess ideally they should approximate to same values (?)

Try online calculators and see if you get the same result 
(http://www.socscistatistics.com/tests/fisher/Default2.aspx)

**Comment by dschslava** [comment]
Thank you for the insights! I'll play with the online calculators and see how I can reconcile the differences.
