### ISSUE TITLE
Reported kataegis foci don't always correspond to regions of hypermutation

### ISSUE THREAD

**Issue by pwaltman** [PoisonAlien/maftools#13]
I've manually verified this, but it appears that the rainfallPlot function just returns the the foci that are identified by the cpt.mean function in the changepoint package. However, the points that the cpt.mean function returns are only that - the points where the distribution changes. In some cases, the points that are returned are points that correspond to an **increase** in the distance between foci. For example, this may happen if there is a region of kataegis between foci 51 and 75. In this case, both points will be returned, however, we care about the region, rather than the specific point.  In cases like this, a user will be able to infer the regions.  

However, I've also observed cases, where it appears that the reported foci represents an increase in distance between SNPS, but is **lacking** a 'leading foci' that corresponds to the start of a region of hypermutation.

I've also observed cases where the 'regions of hypermutation' don't represent a tight clustering of foci, i.e. the distance between SNPs is still quite large (1000+ nt between SNPs).

**Comment by PoisonAlien** [comment]
Hi ,
Yes! All of the above mentioned points are valid. Proper method would be to look at the segments rather than just the change points. I have tried different methods, for instance CBS segmentation and cumulative segmentation (which are intended for copy number data), but they are sensitive to low mutation burden and often results in false positives in this case. 

As you have mentioned, user would be able infer segments from adjacent change points (with help of generated plot), however I too have observed instances where changepoint would simply return start locus or end locus.  But, of all the methods I have tried on available datasets, this method seem to give reasonable result. I am also restricted in new datasets to verify results. 

I'm currently working on an improvised method as described in original nature article by Alexandrov et al 2013, it should be up soon. Meanwhile I would really appreciate if you have any suggestion on the issue.
