### ISSUE TITLE
Error reading maf file

### ISSUE THREAD

**Issue by andyjslee** [PoisonAlien/maftools#157]
I get the following error:

```
reading maf..
Error in validateMaf(maf = maf, isTCGA = isTCGA, rdup = removeDuplicatedVariants,  : 
  missing required fields from MAF: Hugo_Symbol
```
There are no # lines in my maf file
The first line is as follows (tab delimited):
Hugo_Symbol Entrez_Gene_Id  Center  NCBI_Build  Chromosome  Start_position  End_position    Strand  Variant_Classification  Variant_Type    Reference_Allele    Tumor_Seq_Allele1   Tumor_Seq_Allele2   dbSNP_RS    dbSNP_Val_Status    Tumor_Sample_Barcode    Matched_Norm_Sample_Barcode Match_Norm_Seq_Allele1  Match_Norm_Seq_Allele2  Tumor_Validation_Allele1    Tumor_Validation_Allele2    Match_Norm_Validation_Allele1   Match_Norm_Validation_Allele2   Verification_Status Validation_Status   Mutation_Status Sequencing_Phase    Sequence_Source Validation_Method   Score   BAM_file    Sequencer   Tumor_Sample_UUID   Matched_Norm_Sample_UUID    Genome_Change   Annotation_Transcript   Transcript_Strand   Transcript_Exon Transcript_Position cDNA_Change Codon_Change    Protein_Change  Other_Transcripts   Refseq_mRNA_Id  Refseq_prot_Id  SwissProt_acc_Id    SwissProt_entry_Id  Description UniProt_AApos   UniProt_Region  UniProt_Site    UniProt_Natural_Variations  UniProt_Experimental_Info   GO_Biological_Process   GO_Cellular_Component   GO_Molecular_Function   COSMIC_overlapping_mutations    COSMIC_fusion_genes COSMIC_tissue_types_affected    COSMIC_total_alterations_in_gene    Tumorscape_Amplification_Peaks  Tumorscape_Deletion_Peaks   TCGAscape_Amplification_Peaks   TCGAscape_Deletion_Peaks    DrugBank    ref_context gc_content  CCLE_ONCOMAP_overlapping_mutations  CCLE_ONCOMAP_total_mutations_in_gene    CGC_Mutation_Type   CGC_Translocation_Partner   CGC_Tumor_Types_Somatic CGC_Tumor_Types_Germline    CGC_Other_Diseases  DNARepairGenes_Role FamilialCancerDatabase_Syndromes    MUTSIG_Published_Results    OREGANNO_ID OREGANNO_Values X1000gp3_AA X1000gp3_AC X1000gp3_AF X1000gp3_AFR_AF X1000gp3_AMR_AF X1000gp3_AN X1000gp3_CIEND  X1000gp3_CIPOS  X1000gp3_CS X1000gp3_DP X1000gp3_EAS_AF X1000gp3_END    X1000gp3_EUR_AF X1000gp3_IMPRECISE  X1000gp3_MC X1000gp3_MEINFO X1000gp3_MEND   X1000gp3_MLEN   X1000gp3_MSTART X1000gp3_NS X1000gp3_SAS_AF X1000gp3_SVLEN  X1000gp3_SVTYPE X1000gp3_TSD    ACHILLES_Lineage_Results_Top_Genes  CGC_Cancer.Germline.Mut CGC_Cancer.Molecular.Genetics   CGC_Cancer.Somatic.Mut  CGC_Cancer.Syndrome CGC_Chr CGC_Chr.Band    CGC_GeneID  CGC_Name    CGC_Other.Germline.Mut  CGC_Tissue.Type COSMIC_n_overlapping_mutations  COSMIC_overlapping_mutation_descriptions    COSMIC_overlapping_primary_sites    ClinVar_ASSEMBLY    ClinVar_HGMD_ID ClinVar_SYM ClinVar_TYPE    ClinVar_rs  ESP_AA  ESP_AAC ESP_AA_AC   ESP_AA_AGE  ESP_AA_GTC  ESP_AvgAAsampleReadDepth    ESP_AvgEAsampleReadDepth    ESP_AvgSampleReadDepth  ESP_CA  ESP_CDP ESP_CG  ESP_CP  ESP_Chromosome  ESP_DBSNP   ESP_DP  ESP_EA_AC   ESP_EA_AGE  ESP_EA_GTC  ESP_EXOME_CHIP  ESP_FG  ESP_GL  ESP_GM  ESP_GS  ESP_GTC ESP_GTS ESP_GWAS_PUBMED ESP_MAF ESP_PH  ESP_PP  ESP_Position    ESP_TAC ESP_TotalAAsamplesCovered   ESP_TotalEAsamplesCovered   ESP_TotalSamplesCovered Ensembl_so_accession    Ensembl_so_term Familial_Cancer_Genes_Reference Familial_Cancer_Genes_Synonym   HGNC_Accession.Numbers  HGNC_CCDS.IDs   HGNC_Chromosome HGNC_Date.Modified  HGNC_Date.Name.Changed  HGNC_Date.Symbol.Changed    HGNC_Ensembl.Gene.ID    HGNC_Ensembl.ID.supplied.by.Ensembl.    HGNC_Enzyme.IDs HGNC_Gene.family.description    HGNC_HGNC.ID    HGNC_Locus.Group    HGNC_Locus.Type HGNC_Name.Synonyms  HGNC_OMIM.ID.supplied.by.NCBI.  HGNC_Previous.Names HGNC_Previous.Symbols   HGNC_Primary.IDs    HGNC_Pubmed.IDs HGNC_Record.Type    HGNC_RefSeq.supplied.by.NCBI.   HGNC_Secondary.IDs  HGNC_Status HGNC_Synonyms   HGNC_UCSC.ID.supplied.by.UCSC.  HGNC_UniProt.ID.supplied.by.UniProt.    HGNC_VEGA.IDs   HGVS_coding_DNA_change  HGVS_genomic_change HGVS_protein_change ORegAnno_bin    UniProt_alt_uniprot_accessions  annotation_transcript   build   ccds_id dbNSFP_1000Gp1_AC   dbNSFP_1000Gp1_AF   dbNSFP_1000Gp1_AFR_AC   dbNSFP_1000Gp1_AFR_AF   dbNSFP_1000Gp1_AMR_AC   dbNSFP_1000Gp1_AMR_AF   dbNSFP_1000Gp1_ASN_AC   dbNSFP_1000Gp1_ASN_AF   dbNSFP_1000Gp1_EUR_AC   dbNSFP_1000Gp1_EUR_AF   dbNSFP_Ancestral_allele dbNSFP_CADD_phred   dbNSFP_CADD_raw dbNSFP_CADD_raw_rankscore   dbNSFP_ESP6500_AA_AF    dbNSFP_ESP6500_EA_AF    dbNSFP_Ensembl_geneid   dbNSFP_Ensembl_transcriptid dbNSFP_FATHMM_pred  dbNSFP_FATHMM_rankscore dbNSFP_FATHMM_score dbNSFP_GERP.._NR    dbNSFP_GERP.._RS    dbNSFP_GERP.._RS_rankscore  dbNSFP_Interpro_domain  dbNSFP_LRT_Omega    dbNSFP_LRT_converted_rankscore  dbNSFP_LRT_pred dbNSFP_LRT_score    dbNSFP_LR_pred  dbNSFP_LR_rankscore dbNSFP_LR_score dbNSFP_MutationAssessor_pred    dbNSFP_MutationAssessor_rankscore   dbNSFP_MutationAssessor_score   dbNSFP_MutationTaster_converted_rankscore   dbNSFP_MutationTaster_pred  dbNSFP_MutationTaster_score dbNSFP_Polyphen2_HDIV_pred  dbNSFP_Polyphen2_HDIV_rankscore dbNSFP_Polyphen2_HDIV_score dbNSFP_Polyphen2_HVAR_pred  dbNSFP_Polyphen2_HVAR_rankscore dbNSFP_Polyphen2_HVAR_score dbNSFP_RadialSVM_pred   dbNSFP_RadialSVM_rankscore  dbNSFP_RadialSVM_score  dbNSFP_Reliability_index    dbNSFP_SIFT_converted_rankscore dbNSFP_SIFT_pred    dbNSFP_SIFT_score   dbNSFP_SLR_test_statistic   dbNSFP_SiPhy_29way_logOdds  dbNSFP_SiPhy_29way_logOdds_rankscore    dbNSFP_SiPhy_29way_pi   dbNSFP_UniSNP_ids   dbNSFP_Uniprot_aapos    dbNSFP_Uniprot_acc  dbNSFP_Uniprot_id   dbNSFP_aaalt    dbNSFP_aapos    dbNSFP_aapos_FATHMM dbNSFP_aapos_SIFT   dbNSFP_aaref    dbNSFP_cds_strand   dbNSFP_codonpos dbNSFP_fold.degenerate  dbNSFP_genename dbNSFP_hg18_pos.1.coor. dbNSFP_phastCons100way_vertebrate   dbNSFP_phastCons100way_vertebrate_rankscore dbNSFP_phastCons46way_placental dbNSFP_phastCons46way_placental_rankscore   dbNSFP_phastCons46way_primate   dbNSFP_phastCons46way_primate_rankscore dbNSFP_phyloP100way_vertebrate  dbNSFP_phyloP100way_vertebrate_rankscore    dbNSFP_phyloP46way_placental    dbNSFP_phyloP46way_placental_rankscore  dbNSFP_phyloP46way_primate  dbNSFP_phyloP46way_primate_rankscore    dbNSFP_refcodon entrez_gene_id  gencode_transcript_name gencode_transcript_status   gencode_transcript_tags gencode_transcript_type gene_type   havana_transcript   refseq_mrna_id  secondary_variant_classification    ControlRef  ControlAlt  TumorRef    TumorAlt    ControlVAF  TumorVAF    ExAC_AF ESP_AF  X1000G_AF

**Comment by ShixiangWang** [comment]
you can use fread function to read the maf and try using read.maf to read the maf object. wangshx 邮箱：wangshx@shanghaitech.edu.cn 签名由 网易邮箱大师 定制 On 06/13/2018 00:14, Andy Lee wrote: I get the following error: reading maf..
Error in validateMaf(maf = maf, isTCGA = isTCGA, rdup = removeDuplicatedVariants,  : 
  missing required fields from MAF: Hugo_Symbol
 There are no # lines in my maf file The first line is as follows (tab delimited): Hugo_Symbol Entrez_Gene_Id Center NCBI_Build Chromosome Start_position End_position Strand Variant_Classification Variant_Type Reference_Allele Tumor_Seq_Allele1 Tumor_Seq_Allele2 dbSNP_RS dbSNP_Val_Status Tumor_Sample_Barcode Matched_Norm_Sample_Barcode Match_Norm_Seq_Allele1 Match_Norm_Seq_Allele2 Tumor_Validation_Allele1 Tumor_Validation_Allele2 Match_Norm_Validation_Allele1 Match_Norm_Validation_Allele2 Verification_Status Validation_Status Mutation_Status Sequencing_Phase Sequence_Source Validation_Method Score BAM_file Sequencer Tumor_Sample_UUID Matched_Norm_Sample_UUID Genome_Change Annotation_Transcript Transcript_Strand Transcript_Exon Transcript_Position cDNA_Change Codon_Change Protein_Change Other_Transcripts Refseq_mRNA_Id Refseq_prot_Id SwissProt_acc_Id SwissProt_entry_Id Description UniProt_AApos UniProt_Region UniProt_Site UniProt_Natural_Variations UniProt_Experimental_Info GO_Biological_Process GO_Cellular_Component GO_Molecular_Function COSMIC_overlapping_mutations COSMIC_fusion_genes COSMIC_tissue_types_affected COSMIC_total_alterations_in_gene Tumorscape_Amplification_Peaks Tumorscape_Deletion_Peaks TCGAscape_Amplification_Peaks TCGAscape_Deletion_Peaks DrugBank ref_context gc_content CCLE_ONCOMAP_overlapping_mutations CCLE_ONCOMAP_total_mutations_in_gene CGC_Mutation_Type CGC_Translocation_Partner CGC_Tumor_Types_Somatic CGC_Tumor_Types_Germline CGC_Other_Diseases DNARepairGenes_Role FamilialCancerDatabase_Syndromes MUTSIG_Published_Results OREGANNO_ID OREGANNO_Values X1000gp3_AA X1000gp3_AC X1000gp3_AF X1000gp3_AFR_AF X1000gp3_AMR_AF X1000gp3_AN X1000gp3_CIEND X1000gp3_CIPOS X1000gp3_CS X1000gp3_DP X1000gp3_EAS_AF X1000gp3_END X1000gp3_EUR_AF X1000gp3_IMPRECISE X1000gp3_MC X1000gp3_MEINFO X1000gp3_MEND X1000gp3_MLEN X1000gp3_MSTART X1000gp3_NS X1000gp3_SAS_AF X1000gp3_SVLEN X1000gp3_SVTYPE X1000gp3_TSD ACHILLES_Lineage_Results_Top_Genes CGC_Cancer.Germline.Mut CGC_Cancer.Molecular.Genetics CGC_Cancer.Somatic.Mut CGC_Cancer.Syndrome CGC_Chr CGC_Chr.Band CGC_GeneID CGC_Name CGC_Other.Germline.Mut CGC_Tissue.Type COSMIC_n_overlapping_mutations COSMIC_overlapping_mutation_descriptions COSMIC_overlapping_primary_sites ClinVar_ASSEMBLY ClinVar_HGMD_ID ClinVar_SYM ClinVar_TYPE ClinVar_rs ESP_AA ESP_AAC ESP_AA_AC ESP_AA_AGE ESP_AA_GTC ESP_AvgAAsampleReadDepth ESP_AvgEAsampleReadDepth ESP_AvgSampleReadDepth ESP_CA ESP_CDP ESP_CG ESP_CP ESP_Chromosome ESP_DBSNP ESP_DP ESP_EA_AC ESP_EA_AGE ESP_EA_GTC ESP_EXOME_CHIP ESP_FG ESP_GL ESP_GM ESP_GS ESP_GTC ESP_GTS ESP_GWAS_PUBMED ESP_MAF ESP_PH ESP_PP ESP_Position ESP_TAC ESP_TotalAAsamplesCovered ESP_TotalEAsamplesCovered ESP_TotalSamplesCovered Ensembl_so_accession Ensembl_so_term Familial_Cancer_Genes_Reference Familial_Cancer_Genes_Synonym HGNC_Accession.Numbers HGNC_CCDS.IDs HGNC_Chromosome HGNC_Date.Modified HGNC_Date.Name.Changed HGNC_Date.Symbol.Changed HGNC_Ensembl.Gene.ID HGNC_Ensembl.ID.supplied.by.Ensembl. HGNC_Enzyme.IDs HGNC_Gene.family.description HGNC_HGNC.ID HGNC_Locus.Group HGNC_Locus.Type HGNC_Name.Synonyms HGNC_OMIM.ID.supplied.by.NCBI. HGNC_Previous.Names HGNC_Previous.Symbols HGNC_Primary.IDs HGNC_Pubmed.IDs HGNC_Record.Type HGNC_RefSeq.supplied.by.NCBI. HGNC_Secondary.IDs HGNC_Status HGNC_Synonyms HGNC_UCSC.ID.supplied.by.UCSC. HGNC_UniProt.ID.supplied.by.UniProt. HGNC_VEGA.IDs HGVS_coding_DNA_change HGVS_genomic_change HGVS_protein_change ORegAnno_bin UniProt_alt_uniprot_accessions annotation_transcript build ccds_id dbNSFP_1000Gp1_AC dbNSFP_1000Gp1_AF dbNSFP_1000Gp1_AFR_AC dbNSFP_1000Gp1_AFR_AF dbNSFP_1000Gp1_AMR_AC dbNSFP_1000Gp1_AMR_AF dbNSFP_1000Gp1_ASN_AC dbNSFP_1000Gp1_ASN_AF dbNSFP_1000Gp1_EUR_AC dbNSFP_1000Gp1_EUR_AF dbNSFP_Ancestral_allele dbNSFP_CADD_phred dbNSFP_CADD_raw dbNSFP_CADD_raw_rankscore dbNSFP_ESP6500_AA_AF dbNSFP_ESP6500_EA_AF dbNSFP_Ensembl_geneid dbNSFP_Ensembl_transcriptid dbNSFP_FATHMM_pred dbNSFP_FATHMM_rankscore dbNSFP_FATHMM_score dbNSFP_GERP.._NR dbNSFP_GERP.._RS dbNSFP_GERP.._RS_rankscore dbNSFP_Interpro_domain dbNSFP_LRT_Omega dbNSFP_LRT_converted_rankscore dbNSFP_LRT_pred dbNSFP_LRT_score dbNSFP_LR_pred dbNSFP_LR_rankscore dbNSFP_LR_score dbNSFP_MutationAssessor_pred dbNSFP_MutationAssessor_rankscore dbNSFP_MutationAssessor_score dbNSFP_MutationTaster_converted_rankscore dbNSFP_MutationTaster_pred dbNSFP_MutationTaster_score dbNSFP_Polyphen2_HDIV_pred dbNSFP_Polyphen2_HDIV_rankscore dbNSFP_Polyphen2_HDIV_score dbNSFP_Polyphen2_HVAR_pred dbNSFP_Polyphen2_HVAR_rankscore dbNSFP_Polyphen2_HVAR_score dbNSFP_RadialSVM_pred dbNSFP_RadialSVM_rankscore dbNSFP_RadialSVM_score dbNSFP_Reliability_index dbNSFP_SIFT_converted_rankscore dbNSFP_SIFT_pred dbNSFP_SIFT_score dbNSFP_SLR_test_statistic dbNSFP_SiPhy_29way_logOdds dbNSFP_SiPhy_29way_logOdds_rankscore dbNSFP_SiPhy_29way_pi dbNSFP_UniSNP_ids dbNSFP_Uniprot_aapos dbNSFP_Uniprot_acc dbNSFP_Uniprot_id dbNSFP_aaalt dbNSFP_aapos dbNSFP_aapos_FATHMM dbNSFP_aapos_SIFT dbNSFP_aaref dbNSFP_cds_strand dbNSFP_codonpos dbNSFP_fold.degenerate dbNSFP_genename dbNSFP_hg18_pos.1.coor. dbNSFP_phastCons100way_vertebrate dbNSFP_phastCons100way_vertebrate_rankscore dbNSFP_phastCons46way_placental dbNSFP_phastCons46way_placental_rankscore dbNSFP_phastCons46way_primate dbNSFP_phastCons46way_primate_rankscore dbNSFP_phyloP100way_vertebrate dbNSFP_phyloP100way_vertebrate_rankscore dbNSFP_phyloP46way_placental dbNSFP_phyloP46way_placental_rankscore dbNSFP_phyloP46way_primate dbNSFP_phyloP46way_primate_rankscore dbNSFP_refcodon entrez_gene_id gencode_transcript_name gencode_transcript_status gencode_transcript_tags gencode_transcript_type gene_type havana_transcript refseq_mrna_id secondary_variant_classification ControlRef ControlAlt TumorRef TumorAlt ControlVAF TumorVAF ExAC_AF ESP_AF X1000G_AF — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by PoisonAlien** [comment]
Hi,
Could you post your `sessionInfo` ?
