### ISSUE TITLE
Oncoplot: order by variant but only display CNs

### ISSUE THREAD

**Issue by lbeltrame** [PoisonAlien/maftools#239]
The reason for this stems from a request from the wet lab people that called the oncoprints with CN and mutations overlapped "confusing" (there are a lot of events in our samples). I can easily do one with variants only but not the same for CNVs.

I know this is probably doable by myself, but (admittedly) maftools does a lot of the heavy lifting already such as ordering samples, setting up the heatmap properly, etc. 

It would be likely a waste to reimplement 90% of the functionality that is there. If this is unreasonable (and may be, since it's not directly related to what the package does), would you be able to point at what code I could reuse for this? Thanks.

**Comment by PoisonAlien** [comment]
Hello, 
I would be happy to push a commit for this. Something like `hide_variant_classifications` argument which will skip the provided values. 

Of-course you could do it by yourself. 

1. You can change `col = "gray70"` in this line of [code](https://github.com/PoisonAlien/maftools/blob/master/R/oncoplot.R#L284) which will color-code every variant classification (except amp/del) with gray color thereby camouflaging them with the background color. 

2. Or you could just use `colors` argument in `oncoplot` function to set the colors to gray for all the variant classification categories except for the ones you need to show. 

You can try these (try the second part since its the easy way) and let me know if this is something you wanted.

**Comment by lbeltrame** [comment]
Yes, in principle it works but probably an option would be useful to e.g., remove mutations from the bars or listing samples that are with variants only (I have a few). But as a first approach solution 2 works.

**Comment by PoisonAlien** [comment]
Okay, I can push a fix for this.
