### ISSUE TITLE
annovarToMaf Reference_Allele and Tumor_Seq_Allele1&2 question

### ISSUE THREAD

**Issue by tangshanshaolu** [PoisonAlien/maftools#272]
Hi ：
   I am using annovarToMaf() to convert annovar result to maf file. I see source code in annovarToMaf() where  'Make final maf table':
![image](https://user-images.githubusercontent.com/32194143/55052444-eee65d80-5093-11e9-9827-93c7d15d1b75.png)
I am not very clear why Tumor_Seq_Allele1 = ann$Ref ?  I see some other maf files,  Tumor_Seq_Allele1 and Reference_Allele are different.  I am very confused about this.

Thanks a lot!

**Comment by PoisonAlien** [comment]
Hi,
Since most somatic mutations are assumed to be heterozygous there will be a wild-type allele and a mutant allele. Hence `Tumor_Seq_Allele1` is assigned to reference genotype whereas `Tumor_Seq_Allele2` is a mutant. It really doesn't affect any downstream analysis since `Tumor_Seq_Allele2` is always used. `Tumor_Seq_Allele1` is only kept to be consistent with the [MAF file format](https://docs.gdc.cancer.gov/Data/File_Formats/MAF_Format/).

Hope this helps.
