### ISSUE TITLE
Copy Number-Only Samples Ignored by Oncoplot if Top Set

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#286]
A similar issue was fixed before #282 but I still experience it even if I downloaded from master branch. A self-contained example is:

```r
copyTable <- data.frame(Gene = c("MYC", "EGFR", "EGFR", "EGFR"),
                        Sample = c("John", "John", "David", "Lucas"),
			Status = rep("Amp", 4))

plotData <- data.frame(Hugo_Symbol = c("MYC", "TP53", "NRAS", "KRAS"),
                       Chromosome = '.',
                       Start_Position = '.',
                       End_Position = '.',
                       Reference_Allele = '.',
                       Tumor_Seq_Allele2 = '.',
                       Variant_Classification = rep("Missense_Mutation", 4),
                       Variant_Type = '.',
                       Tumor_Sample_Barcode = c("James", "Chris", "David", "David"))	

MAF <- read.maf(plotData, cnTable = copyTable, removeDuplicatedVariants = FALSE)
oncoplot(MAF, showTumorSampleBarcodes = TRUE, top = 2)

```

The problem happens if `top` is set. If not, then the correct plot is generated. You can simply remove the top parameter in the above example to get the correct plot. It's also concerning to see

```r
Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf
```

when `top` is used.

**Comment by PoisonAlien** [comment]
Hi,

1. Using top argument only applies to mutations. Reason being, in GISTIC results, frequent CNV alterations that are found across all the samples in a cohort belong to passenger genes, which often have no functional impact. If you're reading CN data with mutation data, these genes always come up as top altered (mutated/CN altered). To avoid this, oncoplot with top argument chooses genes based on mutation frequency rather than CN frequency. 

For example dataset from vignette, top altered genes are largely passenger genes which have no functional impact in AML, and they are due to CN deletion. To avoid this bias, top argument chooses genes based on  `MutatedSamples` rather than `AlteredSamples`. Hope my explanation was clear enough.

```r
>getGeneSummary(x = laml.plus.gistic)[order(CNV_total, decreasing = TRUE)][1:10, .(Hugo_Symbol, MutatedSamples, CNV_total)]
Hugo_Symbol MutatedSamples CNV_total AlteredSamples
 1:        EZH2              3        23             24
 2:        CUL1              2        23             24
 3:        GRM8              2        23             25
 4:       GSTK1              2        23             25
 5:     ARHGEF5              1        23             24
 6:       CLCN1              1        23             24
 7:     FAM115A              1        23             23
 8:       HTR5A              1        23             24
 9:       KCNH2              1        23             24
10:        NRF1              1        23             24
```

2. Those warnings are pretty harmless. I will suppress them. They are due to NA's in the plot matrix - which are plotted in gray color.

**Comment by DarioS** [comment]
Oh, it is by design. I wasn't expecting it. Perhaps it should be described on the documentation page. Reading the description of `top` doesn't explicitly state that. It refers to "top genes" but I wouldn't guess that all-CNV genes are excluded just from reading it. Or, it could be discussed in Details.

**Comment by PoisonAlien** [comment]
Yes, makes sense. I will update the docs before the release. 
Thank you.
