### ISSUE TITLE
TiTv: rowsums are not 100%

### ISSUE THREAD

**Issue by Chitanda-Satou** [PoisonAlien/maftools#287]
Hi @PoisonAlien ,

In some cases, I found titv plots are like:
![image](https://user-images.githubusercontent.com/32410912/56346746-691e8380-61f5-11e9-9175-23eb5fd1a25d.png)

By reading the source code and the detailed data, I have found the problems are that some indel mutations were classified as SNP:
![image](https://user-images.githubusercontent.com/32410912/56346927-bd296800-61f5-11e9-8064-1c730f258434.png)

The trouble is located in **annovarToMaf.R** :
![image](https://user-images.githubusercontent.com/32410912/56346973-daf6cd00-61f5-11e9-9aa7-055a0872fbc3.png)

variations as GTGAG>TTGTA or CTA>TTC will be classified as SNPs when treated with the function annovarToMaf.

Do you have any suggestion about this? 
Thank you very much.

**Comment by PoisonAlien** [comment]
Ah, I see..
Thanks for tracking the issue. I'm not sure why annovartomaf misclassified them. I will look into it soon.

**Comment by PoisonAlien** [comment]
Hello,
Is it possible to share an example file ?

**Comment by PoisonAlien** [comment]
Hi,
Your files helped me a lot! It has been a while since I dealt with annovartomaf and I realised author has changed the annotations a bit. I had to make significant changes to the code, but I think its quite stable to use now.

Could you please try it on your files and let me know if it works without any issues ? You will have to install from GitHub.

Thanks again for the files.

**Comment by Chitanda-Satou** [comment]
I have tested the new version annovarToMaf() on abount 10 ANNOVAR text files. It works perfect!

Thanks a lot for the excellent work!

**Comment by PoisonAlien** [comment]
Thanks for confirming. I am closing this issue for now. Please feel free to re-open if necessary.
