### ISSUE TITLE
oncoplot colbar plot y axis higher than 100

### ISSUE THREAD

**Issue by wenluo711** [PoisonAlien/maftools#291]
Hi, 
We generated an oncoplot reviewing top 30 genes. Some samples in the top col bar had higher than 100% accumulated variant classification percentage. Is that expected or does that mean some thing wrong with our data?

![merged_FFPE oncoplot](https://user-images.githubusercontent.com/10236222/56668219-26d5c600-667d-11e9-9d1d-d6654dca9f9b.jpeg)

Thanks!
Wen

**Comment by PoisonAlien** [comment]
Hello,

If you're wondering why the top barplot is higher than the number of genes in the plot, its because tumor burden is calculated based on total mutation in that sample. There is nothing wrong with the data. You can double check this with `getSampleSummary` which shows total variants for every sample. 

Hope this helps.

**Comment by ShixiangWang** [comment]
The top panel gives TMB instead of percentage you thought @wenluo711

**Comment by wenluo711** [comment]
Thanks!
