### ISSUE TITLE
gene.summary in summarizeMaf.R sorts genes based on total mutations regardless whether a gene has high frequency of copy number change

### ISSUE THREAD

**Issue by jyu2012** [PoisonAlien/maftools#338]
checked the summarizeMaf.R function and it looks that gene.summary sorts genes based on total number of mutations instead of total number of mutation + copy number change even a CNV table is added. it seems different from what one expects.

code in summarizeMaf.R:
hs.cast = merge(hs.cast, hs.cast.cnv, by = 'Hugo_Symbol', all = TRUE)[order(total, CNV_total, decreasing = TRUE)]

genes ordered by total, and then cnv_total, however, total field only calculates the number of snvs and totally ignored cnv changes. it sounds to me that it would be more rationale to rank genes based on the total number of alterations (snv+cnv) instead of snv only if one adds a cnv table.

would it make sense? would it possible to update? thanks!

**Comment by PoisonAlien** [comment]
Hello,
Yes, that is the case.
If you're processing GISTIC (or CNV) results it is often the case that hundreds of passenger genes are deleted/amplified across all the samples. These genes tend to spam the top list. Hence the output is primarily sorted with mutations. Since `getGeneSummary` returns the table, you could sort it manually based on the column of your choice.

Hope this helps.
