### ISSUE TITLE
url not working in oncotate.R

### ISSUE THREAD

**Issue by sraorao** [PoisonAlien/maftools#35]
Hi, fyi, I get an error running the `oncotate()` function,

> fetching annotation from Oncotator. This might take a while..
>   |==========================                                                                               |  25%
>  Show Traceback
>  
>  Rerun with Debug
>  Error in file(con, "r") : cannot open the connection 

 and changing line 49 to `rec.url = paste('http://portals.broadinstitute.org/oncotator/mutation',rec,sep = '/')` worked.

**Comment by PoisonAlien** [comment]
Hi,

Thanks for reporting. Does this happen all the time ? I am aware that R tends to loose connection sometime, but this seems to be problem with oncotator API url and oncotator API hasn't [changed](https://portals.broadinstitute.org/oncotator/help/) since long time. Anyways, thank you. I will look into it.

**Comment by PoisonAlien** [comment]
fixed. Thanks again, you were rite about url change. I will ask oncotator team for clarification.
