### ISSUE TITLE
EGFR mutation selection problem

### ISSUE THREAD

**Issue by a00101** [PoisonAlien/maftools#378]
Thanks for maftools.

Below is ouput of ANNOVAR
```
chr7 | 55191822 | 55191822 | T | G | exonic | EGFR | . | nonsynonymous SNV | EGFR:ENST00000454757.6:exon20:c.T2438G:p.L813R,EGFR:ENST00000455089.5:exon20:c.T2438G:p.L813R,EGFR:ENST00000275493.6:exon21:c.T2573G:p.L858R
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
```

I made 'maf' successfully. And I visualize lollipop plot for "EGFR".
But it plotted with L813R mutation. I want to view L858R mutation instead of L813R.

Thanks in advance.

**Comment by PoisonAlien** [comment]
Hi,
Sorry for late reply. `annovarToMaf` function always chooses first transcript for annotation. In your case its `EGFR:ENST00000454757.6`. Of note, its always hard to predict which transcript is being affected. Tools like VEP/vcf2maf do some sort of transcript prioritization to mitigate this issue. Maybe you could try them instead of Annovar? 
Hope this helps.
