### ISSUE TITLE
Interpretation the percentage of top 10 mutated gene in plotmafSummary result

### ISSUE THREAD

**Issue by Gandalfy** [PoisonAlien/maftools#400]
Hi,

Many thanks advanced for this amazing tool, maftools. I am learning it to analyze some mutation data but I am really confused about the percentage of top 10 mutated gene in plotmafSummary result when reading your delicate vignette. I made a screenshot and show it as the follows:

![image](https://user-images.githubusercontent.com/26314649/66729890-dea39d80-ee80-11e9-8583-6f54c42907e7.png)

You could obviously see that 25% has a little bit longer than 27% regarding the bar length, or TET2 (9%) has longer bar length than that of IDH2 (10%). This is really confusing and how to interpret that? What does this percentage value mean?

Thank you.

**Comment by PoisonAlien** [comment]
Hi,
Please accept my apologies for the late reply. Regarding the issue, the bars are ordered according to values on x-axis (total number of mutations). Annotations to the right depict `%` of samples which are altered in the cohort. You can see the details with the function `getGeneSummary`.

```r
> getGeneSummary(x = laml)[1:5,.(Hugo_Symbol, total, MutatedSamples)]
Hugo_Symbol total MutatedSamples
1:        FLT3    52             52
2:      DNMT3A    54             48
3:        NPM1    34             33
4:        IDH2    20             20
5:        IDH1    18             18
```

Above table shows `FLT3` is mutated in 52 samples of 192 (~27%). `DNMT3A` is mutated in 48 samples (~25%) however due to multihit variants its has more mutations (54).

I hope this was clear. Please let me know if you have any followup questions.
