### ISSUE TITLE
struggle with cosmic mutational signature extaction

### ISSUE THREAD

**Issue by guohe113** [PoisonAlien/maftools#436]
It went well before the 2019-10-29 update
but using the new version , it goes wrong every time whenever goes to 
laml.og30.cosm = compareSignatures(nmfRes = laml.sig, sig_db = "legacy")
with the error message "Error in compareSignatures(nmfRes = laml.sig, sig_db = "legacy")"
laml.sig = oncodrive(maf = laml, AACol = 'Protein_Change', minMut = 5, pvalMethod = 'zscore')
I'm wondering is there any mistake in the comand.

**Comment by guohe113** [comment]
should it be 'laml.sign' or 'laml.sig'?

**Comment by PoisonAlien** [comment]
You are getting confused with the commands. `oncodrive` is the function which identifies the potential driver genes and it has nothing to do with `compareSignatures`. 
`compareSignatures` works with the output from `extractSignatures`.

**Comment by guohe113** [comment]
Got it, thank you. Sometimes, when plotSignatures, same cosmic signature showed up twice, with different cosine-similarity. Like the results shown below. How to deal with such results? I'm expecting each signature showed up only once.
![image](https://user-images.githubusercontent.com/49849478/70201365-5c817800-1751-11ea-81b1-72002344e207.png)

**Comment by PoisonAlien** [comment]
Hi,
Since the extracted signatures are de-novo signatures , you might be finding something novel which hasn't been described before; and the best possible match from known signatures is COSMIC_1. However at this point its hard to expect new signatures. Can you try to run `compareSignatures` with `sig_db = "SBS"`, maybe this will help to see if these are already reported before.
