### ISSUE TITLE
extractSignatures arguments lost and NMF error

### ISSUE THREAD

**Issue by t-neumann** [PoisonAlien/maftools#441]
Hi,

I had a perfectly working version of extracting mutational signatures for my data. I then pulled in a recent commit for a bugfix you did for me and now the functions are not working anymore and from the help it looks like you removed some parameters such as `nTry` from the function.

```
> dat.tnm = trinucleotideMatrix(maf = dat, ref_genome = "BSgenome.Hsapiens.UCSC.hg38")
-Extracting 5' and 3' adjacent bases
-Extracting +/- 20bp around mutated bases for background C>T estimation
-Estimating APOBEC enrichment scores
--Performing one-way Fisher's test for APOBEC enrichment
---APOBEC related mutations are enriched in  0 % of samples (APOBEC enrichment score > 2 ;  0  of  28  samples)
-Creating mutation matrix
--matrix of dimension 28x96

> dat.sign = extractSignatures(mat = dat.tnm, plotBestFitRes = FALSE, parallel = 'P4')
-Running NMF for factorization rank: 
Error in .local(x, rank, method, ...) : 
  NMF::nmf - Argument `seed` must be an NMF model when argument `rank` is missing.
```

Any ideas?

**Comment by PoisonAlien** [comment]
I did not remove any arguments, however I added couple of arguments to `estimateSignatures` function. Are you sure about `extractSignatures` function?

**Comment by t-neumann** [comment]
I see - I missed this change, sorry for that. I tried to run it, but run into a different problem now with the new functions:

```
data.sign = estimateSignatures(mat = data.tnm, nTry = 6, plotBestFitRes = FALSE, parallel = 4)
-Running NMF for 6 ranks
-Finished in 00:08:27 elapsed (34.8s cpu) 

data.og30.cosm = compareSignatures(nmfRes = data.sign, sig_db = "legacy")
Error in 1:ncol(w) : argument of length 0

```

From what I can see the problem is the following line:

```
w = nmfRes$signatures
```

It looks like from the `data.sign` object the `signatures` attribute is missing.

**Comment by PoisonAlien** [comment]
Sorry things seem to be complicated after the update (an additional required step is missing in vignette, which I have to fix). 
`estimateSignatures` only helps to get an idea of optimal number of signatures. After `estimateSignatures`, use its output with `plotCophenetic`  to draw the elbow plot, which should help you decide the number of signature. Once you get this number, you will have to finally run `extractSignatures`. 

So its a three step process instead of one as in previous versions

`estimateSignatures` -> `plotCophenetic` (and decide `n`) -> `estimateSignatures` -> `compareSignatures` and `plotSignatures`

Hope this helps. Please let me know if you have any questions.

**Comment by t-neumann** [comment]
Ok that was a bit confusing because in the current version of the vignette the `extractSignatures` was not explicitely used in the example. You might want to consider adding this. Thanks for the clarification!
