### ISSUE TITLE
Problems with detect kataegis in rainfallPlots

### ISSUE THREAD

**Issue by JocelynSP** [PoisonAlien/maftools#460]
Hi, I had a couple of problems with detecting kataegis. I have a cohort of 220 samples, and when I processed them 13 failed to terminate. The problem appears to be that 
while(end_idx <= nrow(chr.dat))
is not checked while extending a kataegis queue, so if the last SNV is inside the kataegis region it keeps adding non-existent SNVs without changing mean(diff)).
I made a change which fixed this, and then looping through all samples with savePlot = TRUE crashed due to too many open devices.
I have made a pull request with suggested fixes
Thanks for a very nice set of tools,
Jocelyn

**Comment by PoisonAlien** [comment]
I have only merged changes made to `detectKataegis` and plot saving part of the PR. I couldnt accept modifications regards chromosome names since it breaks several function which rely on the presence/absence of `chr` prefix. I understand the current implementation is not perfect, and I should be using factors/levels - but for now I am going to keep it that way. Slowly I will change them. Thank you again.
