### ISSUE TITLE
RFE: Allow subsetting samples in the GISTIC class

### ISSUE THREAD

**Issue by lbeltrame** [PoisonAlien/maftools#534]
As the issue subject says, it might be useful to subset samples in GISTIC objects, similar to what it is done for MAFs. A use case I have is a global analysis I made with GISTIC, but I want to display the individual alterations in two different oncoplots basing on some clinical data.

**Comment by PoisonAlien** [comment]
I have been trying to implement it but it seems it does not make sense to subset GISTIC object because the statistics such as p-values, amplitude, g-scores, etc are all estimated on the original cohort and can not be subsetted (or recalculated in R). 
Even you subset for specific samples you will end up with faulty values.

**Comment by ShixiangWang** [comment]
If it is truly important, maybe we can consider providing GisticCompare for two or more gistic objects. It should make sense.

**Comment by PoisonAlien** [comment]
Yeah something like `GisticCompare` should be a better option. 
Also you can just add clinical parameter as one of the annotation row which should be suffice and show the differences between groups.
