### ISSUE TITLE
The cohort size would be 0 after subsetmaf function 

### ISSUE THREAD

**Issue by entcai** [PoisonAlien/maftools#535]
Dear PoisonAlien

**Describe the issue**
I am a new maftools user. I found my maf file will lose sample size information after I subset with the parameter tsb= a list of TCGA barcodes. There is no percentage in My plotmafSummary plot[Inf%]. A similar result happened in oncoplot, But I can add cohortsize= to solve the problem.

**Command**
laml.1 = read.maf(maf = 'f:/TCGA/pan-cancer/Resource/HNSC-CESC-mutation/CESC/TCGA.CESC.mutect.somatic.maf.gz')

laml.1@data$Tumor_Sample_Barcode=substr(laml.1@data$Tumor_Sample_Barcode,1,12)

CESC.Mu=subsetMaf(laml.1,tsb = clin$ParticipantBarcode)
plotmafSummary(maf = CESC.Mu, rmOutlier = TRUE,showBarcodes = FALSE,
               addStat = 'median', dashboard = TRUE, titvRaw = FALSE)
![image](https://user-images.githubusercontent.com/59844067/82870839-97918680-9efe-11ea-8dc9-6e06448cccde.png)

I appreciate it if any suggestions

Best,

**Comment by PoisonAlien** [comment]
Hello,
You should not cut your TSB's with `substr` in the maf object. There is an argument `isTCGA` in `read.maf` which exactly does this. Could you try the below function and let me know if you still have the issue?

```r
laml.1 = read.maf(maf = 'f:/TCGA/pan-cancer/Resource/HNSC-CESC-mutation/CESC/TCGA.CESC.mutect.somatic.maf.gz', isTCGA = TRUE)
```

**Comment by beginner984** [comment]
hello @PoisonAlien  I saw this post about subset maf so I thought to ask my question here, sorry I should create a new post

I have maf file and maf object from a very big data, I want to subset only non-silent mutations

I saw see

`subsetMaf(maf = laml, genes = c('DNMT3A', 'NPM1'), mafObj = FALSE,query = "Variant_Classification == 'Splice_Site'")`

I don't know how to adapt this to my case, I mean I don't what I should replace instead of splice_site ignoring genes argument

please, you may help as always

thank you very much

**Comment by PoisonAlien** [comment]
@beginner984 
Your maf object contains `data` slot which has all non-silent mutations, and `maf.silent` slot containing all silent mutations. In your case you dont need to subset. 
The example you are referring to only subsets by certain type of `Variant_Classification` type.

**Comment by beginner984** [comment]
Thank you

Actually I need a list of mutations (`REF ALT`) which are `SNP` and `non-silent` from my maf because I want to intersect only these mutations from another genomic coordinate file

So, if I got the point properly, I must extract `data slot` from my maf and write the SNPs from that as an output?

**Comment by PoisonAlien** [comment]
Yes, or you could also do the following

```r
subsetMaf(maf = laml, query = "Variant_Type == 'SNP'", includeSyn = FALSE, mafObj = FALSE)
```

**Comment by entcai** [comment]
> Hello,
> You should not cut your TSB's with `substr` in the maf object. There is an argument `isTCGA` in `read.maf` which exactly does this. Could you try the below function and let me know if you still have the issue?
> 
> ```r
> laml.1 = read.maf(maf = 'f:/TCGA/pan-cancer/Resource/HNSC-CESC-mutation/CESC/TCGA.CESC.mutect.somatic.maf.gz', isTCGA = TRUE)
> ```

That solved my question. Thank you. Before that, I tried 'isTCGA = TRUE' in subsetMaf function which will have errors like
 'Error in dcast.data.table(data = vc, formula = Tumor_Sample_Barcode ~  : 
  Can not cast an empty data.table'.

If anyone has the similar question on this, 'isTCGA = TRUE' in read.maf function should address it.

Thank you. I very appreciate it.
