### ISSUE TITLE
Adding the SV subclass in Oncoplot as well

### ISSUE THREAD

**Issue by snashraf** [PoisonAlien/maftools#543]
Hello,

I am wondering if there is a way to integrate/include SV generated using DELLY, MANTA like DEL, DUPLICATION etc in oncoplot as well apart from CNV and SNV data?

Regards,
Najeeb

**Comment by PoisonAlien** [comment]
Thanks for the files. I will look into them probably over the weekend. 
I will have to read more but, what kind of SVs are these? Translocations or inversions or ..?

**Comment by beginner984** [comment]
Actually `Manta` calls the `SV` and if I am not wrong, each .vcf can contain different types of `chromosomal rearrangement` like `Translocations` or `inversions` as `Strelka mutation caller` calls `insertion` and `deletion` as INDEL in a .vcf file. To be honest I am not good in these things I just think visualisation of SVs as maftools does for mutations could have a hug impact of genomic visualisation because visualising SVs via circos plot or whatever is not simple at all and I have found almost no user friendly software for that as we have maftools for copy number and mutations.

**Comment by DrZhaoJie** [comment]
Hello,
I also want to follow that the visualization of SVs by circos plot was available?

**Comment by PoisonAlien** [comment]
This unfortunately lies outside the scope of `maftools`. In addition there seems to be no standard file format and parsing VCF files is not so trivial. Hence closing the issue.
