### ISSUE TITLE
tcgaCompare seems to get the wrong samples in plot

### ISSUE THREAD

**Issue by 2236529177** [PoisonAlien/maftools#544]
laml.mutload = tcgaCompare(maf = laml, cohortName = 'Example-LAML')

1   I calculate the sample number in excel , it is 193,not 192

2  **capture_size:** capture size for input MAF in MBs. Default NULL. If provided plot will be scaled to mutations per mb.
  **tcga_capture_size   : T**CGA capture size is assumed to be 50mb.

without default capture_size, how can calculate the Example-LAML TMB?  and people usually say tcga capture size is 38, bot 50

3  in maf file. do you count each variant in a sample without filtering, such as filter silent,and I think teh tmb you calculate is a little big. and has the tmb in plot been loged? 

![image](https://user-images.githubusercontent.com/25199946/83935755-1fc13700-a7ef-11ea-91fd-c332741a7fdb.png)

**Comment by 2236529177** [comment]
does the y-axis stands for the number of genes ,so 10^-1=0.1, how should I interprete this, thanks a lot

![image](https://user-images.githubusercontent.com/25199946/83938322-d3352600-a805-11ea-9695-2be403fa7bd1.png)
![image](https://user-images.githubusercontent.com/25199946/83938329-dfb97e80-a805-11ea-8926-1d76d45f8bbe.png)

**Comment by PoisonAlien** [comment]
Hi,

1. Function removes samples with zero mutations be default. Setting `rm_zero = FALSE` shows 193.
2. Without capture size mutation burden is not normalized to per MB. They will be just median values. There is no solid way of knowing TCGA capture size, it depends on who you ask. Default value of 50MB is based on [agilent sureselect kit](https://www.agilent.com/en-eu/promotions/sureselect-human-all-exon-v7). You can set it 38 or of your choice. 
3. Only non-synonymous mutations are used. 

For gistic results; negative sign indicates deletions. Its just `10^1` with sign reversed.

**Comment by 2236529177** [comment]
thanks a lot.
1 bubble is according to -log10 transformed q values, so can you give a q_value bar on the plot?

you said negative sign indicates deletions, so what the y-axis mean, can you describle it clearly

thanks a lot

**Comment by PoisonAlien** [comment]
1. I realised that plot had no scale for q values. I have added it now. Maybe it will help.
2. They are number of genes amplified (above zero) or deleted (below zero). Anyway I now made it to draw absolute values since it seems confusing. If you dont want log scale set `log_y = FALSE`
3. Its which bands to be labelled among all. By default it shows top 5 (based on q values). This argument doesnt take `all` as an option. You will have to provide names of the bands to highlight. Use `getCytobandSummary()` to get the summary. 
I have made it more flexible now (you can set it to `all` or any number top bands or names of the cytobands.

**Comment by 2236529177** [comment]
so i nedd to install from tyhe github now, am I right?

**Comment by PoisonAlien** [comment]
Yes, that is correct.
```r
remotes::install_github(repo = "poisonalien/maftools")
```

**Comment by 2236529177** [comment]
thanks a lot, I have tested that, wonderful, thanks a lot
