### ISSUE TITLE
Setnames error in oncoplot

### ISSUE THREAD

**Issue by abkhan90** [PoisonAlien/maftools#600]
**Describe the issue**
When I run the oncoplot command I get the error:

```
> oncoplot(maf = smoker, top = 10)
Error in setnames(x, value) : 
  Passed a vector of type 'integer'. Needs to be type 'character'.
```

My workflow was:
1) Merge multiple MAF files using Mac command line concatenate function
2) Import merged MAF file as a text file into R
3) I had to manually add column names to the MAF file
4) Used
`> smoker = read.maf(maf = Smoker.Merged)`

5) Plotted the summary, which gave graphs but also returned the below error. 
```
> plotmafSummary(maf = smoker, rmOutlier = TRUE, addStat = 'median', dashboard = TRUE, titvRaw = FALSE)
Warning message:
In titv(maf = maf, useSyn = TRUE, plot = FALSE) :
  Non standard Ti/Tv class: 1TRUE
```

Many thanks in advance

**Command**
Please post your commands and the output (errors or any unexpected output)

> oncoplot(maf = smoker, top = 10)
Error in setnames(x, value) : 
  Passed a vector of type 'integer'. Needs to be type 'character'.

**Session info**
Run `sessionInfo()` and post the output below

```
SessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.6
```

**Comment by PoisonAlien** [comment]
Hi,
Few things.. I would recommend using `merge_mafs` function from maftools for merging. It takes care of column headers and binds by matching column names. Warning in TiTv is because there are some non ATGC values for SNVs in your maf (I think they must be column headers from each file when you had merged them from `cat` function). 
What version of maftools are you using? Also try to install the tool from GitHub (for recent updates) and let me know if the above steps still leads to error.
