### ISSUE TITLE
The version of human genome maftools is using

### ISSUE THREAD

**Issue by Mussa1122** [PoisonAlien/maftools#604]
Hello

If this is true that Maftools uses `hg38`? If so, my data has ben hg19, how much my results would change?

**Comment by PoisonAlien** [comment]
Hi,
Could you please maybe include bit more details. What functions are you referring to?

**Comment by beginner984** [comment]
Thank you

Today I saw this post in Biostars 

https://www.biostars.org/p/459770/
by which I really got panicked because I have made a lot of conclusion from my analysis so far using almost all of maftools functionalities especially GISTIC reading 

This post caused I asked myself if Maftools works differently based on the human genome versions

**Comment by PoisonAlien** [comment]
Only `gisticChromPlot` uses chromosome length information for plotting. Default is `hg19` and can be changed with `ref.build` argument.
