### ISSUE TITLE
Oncoplot including synonymous(silent) mutation and TMB calculation including synonymous(silent) mutation

### ISSUE THREAD

**Issue by DrZhaoJie** [PoisonAlien/maftools#610]
Deat Prof.
        I really enjoy your maftools package. I want to use it to calculate tumor mutation burden. And I found that maf$variants.per.sample only provided total number of  Missense_Mutation+Nonsense_Mutation+Nonstop_Mutation 
+Splice_Site+Translation_Start_Site. Do you classify these mutaion types into non-synonymous mutation (figure1)? And maf$variants.per.sample was the TMB of each sample?  How about synonymous mutations? Do you classify them into melanomamaf@maf.silent file (figure2)? How can I draw the Oncoplot including synonymous(silent) mutation as well as copy number variation? Synonymous (silent) mutation of each sample may be calculated through melanomamaf@maf.silent file, right? Sincerely, Thank you very much!
![image](https://user-images.githubusercontent.com/55881098/93080273-00745880-f6c0-11ea-878e-0e2a682af4ab.png)

**Comment by PoisonAlien** [comment]
Hi,

1. Yes by default variant classifications with functional impact are classified as non-synonymous. Take a look at `?read.maf` especially `vc_nonSyn` argument if you want to consider your own list variant classification as `non-synonymous`

2. Yes, and silent mutations are not considered for summary. If you want a complete summary try `mafSummary` function.

3. CN events should be included as GISTIC results or as a 3 column data.frame with CN status for each gene. Please refer to `cnTable` argument in `read.maf`. It is not so direct to plot silent variants into oncoplot. If you would like to draw them, you can consider them as non-syn using `vc_nonSyn` argument of read.maf

P.S: You dont have to address me as Prof, because I am not one :D

**Comment by DrZhaoJie** [comment]
haha. I really appreciate it that you replied so timely! Thank you very much!  I'm sorry that I didn't list my questions as number 1,2,3.  
1.  I did it with the following codes:
     Look, I added "Silent","3'UTR","5'UTR" for example. But the oncoplot only shows "Silent". Why?
     melanomamaftest <- read.maf(melanomamaf, vc_nonSyn = c("Frame_Shift_Del", "Frame_Shift_Ins",
          "Splice_Site", "Translation_Start_Site","Nonsense_Mutation", "Nonstop_Mutation", 
          "In_Frame_Del","In_Frame_Ins", "Missense_Mutation","Silent","3'UTR","5'UTR"),
          gisticAllLesionsFile = "all_lesions.conf_99.txt",
          gisticAmpGenesFile = "amp_genes.conf_99.txt",
          gisticDelGenesFile = "del_genes.conf_99.txt",
          gisticScoresFile = "scores.gistic")
    oncoplot(maf = NSCLCmaftest, top = 10)
![image](https://user-images.githubusercontent.com/55881098/93106598-0fb8cd80-f6e3-11ea-9baa-597f298995a6.png)

2.  One more question, in some literature, the mutation burden was estimated as (total mutation/total covered bases) × 
   10^6. Do you agree with this? Or do you agree that maf$variants.per.sample was the non-synonymous TMB of each 
   sample?
Thank you very much!

**Comment by PoisonAlien** [comment]
1. It depends on you data. Seems like you have more `Silent` variants in top 20 genes than other types. You can check with `getGeneSummary()`

2. There are already couple of functions to estimate/compare TMB. `tcgaCompare` and `tmb` both of which normalizes for capture size. Please see all the functions in `maftools` for reference.
