### ISSUE TITLE
tcgaCompare Default Size Suitability

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#612]
The default is `tcga_capture_size = 50`. I download the MC3 BED file of the capture regions. It seems that the exome is capturing about 94 megabases, so this default doesn't seem suitable.

```r
r=import("TCGAregions.bed")
r=unique(r) # Some ranges are repeated
r=reduce(r) # Some are overlapping.
sum(width(r)) / 1000000
[1] 94.6363
```

**Comment by PoisonAlien** [comment]
haha.. I just checked this yesterday.. I will update this soon. 
I still wonder if this is the true capture size or they are just using all the exon intervals (seems to be the case). Earlier capture kits were 35MB if I remember correctly and then came the sureselect 50MB.

**Comment by DarioS** [comment]
Oh, I didn't realise that the exome sequencing was almost as inconsistent as the whole genome sequencing. I am comparing ESCA and LUSC and when I investigate I find that ESCA uses "Nimblegen SeqCap EZ Human Exome Library v3.0 64 Mb" and LUSC uses "Agilent SureSelect Human All Exon 50 Mb". `tcga_capture_size` could perhaps accept a vector of values.

**Comment by PoisonAlien** [comment]
This gets messier and messier. We should harmonize this. How about if I take all MC3 variants and subset it for 50MB sureselect regions. That what would bring it all to the same scale - since it is most commonly used kit and also overlaps/extends the updated kits.

**Comment by beginner984** [comment]
@PoisonAlien and @DarioS 

Although may seem irrelevant but I need your suggestion please

If a program which predicts microsattelite instability takes `exome_size=44` for TCGA cohort, and I have whole genome sequencing, how I know what I should put here instead of `44`?

**Comment by DarioS** [comment]
I don't know but probably 3100. Or, just use software which is specifically designed for whole genome sequencing such as [PURPLE](https://github.com/hartwigmedical/hmftools/tree/master/purity-ploidy-estimator).

```
purity	normFactor	score	diploidProportion	ploidy	gender	status	polyclonalProportion	minPurity	maxPurity	minPloidy	maxPloidy	minDiploidProportion	maxDiploidProportion	version	somaticPenalty	wholeGenomeDuplication	msIndelsPerMb	msStatus	tml	tmlStatus	tmbPerMb	tmbStatus
0.8400	0.6500	1.0147	0.0003	3.1721	MALE	NORMAL	0.3357	0.8000	0.9000	3.1188	3.1862	0.0003	0.0003	2.41	0.0000	true	0.2714235746764603	MSS	0.0	LOW	4.0465197621546	LOW
```

There is a column heading msStatus with value MSS below it (or possibly MSI).

**Comment by Mussa1122** [comment]
Thank you so much

As the capture size in my data (WGS) is `2820 per mega base`; I have done a test in which I knew the MSI status of a specific sample already for MSIpred software

When I put 2820 in exome_size the status was MSI-H which is correct but when I put that by giga base like 2.82 the status turned to the MSS which is wrong

I tried in giga base because the author of software suggested me to put in gig base

What one should do in such situation please? Any idea?

**Comment by PoisonAlien** [comment]
Hi @DarioS ,
I re calculated TMB for TCGA samples by restricting them to Agilent Sureselct kit (35.8 MB). Now the TMB size should be uniform across TCGA cohorts. See [here](https://github.com/PoisonAlien/maftools/blob/master/scripts/estimate_tcga_tmb.R) for source if you;re interested.

**Comment by XiaofeiSong** [comment]
@PoisonAlien Thanks for the update. This would be very helpful. I re-downloaded the package, but it seems not updated yet. May I ask how to get access to the new TCGA TMB data?

**Comment by PoisonAlien** [comment]
H,
It has already been updated. You can check the file [here](https://github.com/PoisonAlien/maftools/blob/master/inst/extdata/tcga_cohort.txt.gz).  Or from within R using the command 

```r
system.file("extdata", "tcga_cohort.txt.gz", package = "maftools")
```

Following variant classifications are considered for TCGA TMB estimation:

```r
[1] "Frame_Shift_Del"        "Frame_Shift_Ins"        "Splice_Site"           
[4] "Translation_Start_Site" "Nonsense_Mutation"      "Nonstop_Mutation"      
[7] "In_Frame_Del"           "In_Frame_Ins"           "Missense_Mutation" 
```

**Comment by XiaofeiSong** [comment]
Thank you! It's very helpful.

**Comment by beginner984** [comment]
@PoisonAlien My data is WGS for oesophageal adenocarcinoma

Because I am comparing whole-genome with whole-exome data. Are you considering exonic mutations only?

By this function I have placed my two groups of patients (WGS) in the context of 33 different cancer types from TCGA and I got this

<img width="1280" alt="Screenshot 2020-11-05 at 23 40 07" src="https://user-images.githubusercontent.com/43682980/98308564-4531b700-1fc0-11eb-8a0e-1eca78b877ce.png">

I have two groups of patients one with higher mutation burden which respond to chemotherapy and one which does not respond with a lower mutation burden and I want to know which group of my samples are closer to hyper mutated cancers like melanoma

Thank you so much for any suggestion

**Comment by PoisonAlien** [comment]
Hi,
TMB is measured only for non-synonymous mutations. The following variant classifications are considered by default (Unless if you have defined your own variant classifications to be considered as non-synonymous with the argument `vc_nonSyn` in read.maf).

```r
"Frame_Shift_Del", "Frame_Shift_Ins", "Splice_Site", "Translation_Start_Site","Nonsense_Mutation", "Nonstop_Mutation", "In_Frame_Del","In_Frame_Ins", "Missense_Mutation"
```

**Comment by beginner984** [comment]
Thank you so much @PoisonAlien 

In this issue https://github.com/PoisonAlien/maftools/issues/563 you are mentioning:

`Mutational load from TCGA cohorts in tcgaCompare is derived from MC3 maf file. Fortunately MC3 also provides the target BED file. Best way would be subset your MAF object to this BED regions and compare against tcga cohorts.`

Is intersecting my WGS maf with such a `bed file` is still a best option for putting WGS in the context of TCGA or because TMB is measured only for non-synonymous mutations, using WGS in `tcgaCompare` is adjustable?

Thank you so much for any thought

**Comment by PoisonAlien** [comment]
Please read the comments on this issue carefully. TMB from TCGA patients is restricted to Agilent 35 MB kit. You would probably better off subsetting to the BED file Agilent (Agilent_SS_Human_All_Exon_V7 to be specific). You will need to download it from the Agilent site which requires free registration.

**Comment by Mussa1122** [comment]
Thank you so much, so `gencode.v19.basic.exome.bed` file which you have linked to that in that issue, is not appropriate bed file to use for this purpose?
