### ISSUE TITLE
Error in MATH calculation

### ISSUE THREAD

**Issue by DrZhaoJie** [PoisonAlien/maftools#621]
Hi,
I calculated the MATH score with the following code

```r
KIRC01allMATHV0 <- inferHeterogeneity(maf = KIRC01allmaf, tsb = KIRC01allmaf@variants.per.sample$Tumor_Sample_Barcode,
                                      segFile = "KIRC01allsegforMATH.txt", vafCol = 't_vaf')

Error in switch(EXPR = modelName, X = "E", XII = "EII", XXI = "EEI", XXX = "EEE",  : 
  EXPR must be a length 1 vector.
```

When I run the same code for LUAD, it delivered the same error. For other tumor types such as LUSC BLCA, it's ok.
What's the problem? Thank you very much!

**Comment by PoisonAlien** [comment]
Hi,
Its hard to say without a reproducible example. Could you please share an example sample (as an rds file or maf file)? You can attach it here in the issue.

**Comment by DrZhaoJie** [comment]
Hi, these are my R code and maf file for KIRC. Thank you very much!
[Uploading MATH.zip…]()

**Comment by PoisonAlien** [comment]
Hi, I think you forgot to upload it. Its just an empty link which points to nowhere.

**Comment by DrZhaoJie** [comment]
Hi, these are my R code and maf file for KIRC and they were uploaded
[MATH.zip](https://github.com/PoisonAlien/maftools/files/5326985/MATH.zip)
. Thank you very much!

**Comment by PoisonAlien** [comment]
Hi,
Thanks for sharing your data. I could not reproduce your error however. It seems to work fine. 

```r
inferHeterogeneity(maf = KIRC01allmaf, tsb = KIRC01allmaf@variants.per.sample$Tumor_Sample_Barcode)
```

Don't subset sample names manually with `substr`. Because it will change the names, but the factor levels would remain the same as old ones. It will cause discrepancies. Instead while reading maf with `read.maf` use the argument `isTCGA=TRUE` and it will take care of TCGA sample names.

I could not find the segmentation file. But make sure the sample names in segmentation files matches to the names in MAF.

**Comment by DrZhaoJie** [comment]
Hi
![image](https://user-images.githubusercontent.com/55881098/96360357-19ed4200-114f-11eb-9cc3-f6e5b96d2733.png)
I wonder how the mutation rate such as  27% was calculated! Thank you very much!

**Comment by PoisonAlien** [comment]
Hi,
Please see #400 for details.
