### ISSUE TITLE
coanalysis of multiple tumor type

### ISSUE THREAD

**Issue by DrZhaoJie** [PoisonAlien/maftools#627]
Hi, thanks for your contribution to this package, I really enjoy it. And I have two questions.
First, I want to calculate specific gene mutation rate in multiple tumor type and compare them. Do I need to remove batch effect before comparison. If needed, how?
Second, I want to conduct oncoplot(maf = laml, top = 10) on merged maf file of multiple tumor type, for example, mergedmaf <- maftools:::merge_mafs(maf = c(KICHmaf, KIRCmaf, KIRPmaf). Directly oncoplot(maf = mergedmaf, top = 10) is OK? Do I need to remove batch effect? Thank you very much!

**Comment by PoisonAlien** [comment]
Hi,

1. Correct me if I am wrong but,I have not heard of batch effects being a co-variate in variant analysis. Since you are not measuring anything continuous (like expression or methylation) - I am not sure if it really of an issue here. Main concern would be cohort sizes that are being compared but fisher's exact test takes this into account so it should be fine. Also if you're comparing a cohort from captured region vs a WGS/WXS, make sure you are restricting your analysis to common genes which are present in both cohorts. 

2. For visualization you can just merge and plot. It should be fine.

**Comment by DrZhaoJie** [comment]
Thank you! I may agree with you

**Comment by DrZhaoJie** [comment]
Hi, I run your code:
BLCA01laml.gistic = readGistic(gisticAllLesionsFile = all.lesions, gisticAmpGenesFile = amp.genes, gisticDelGenesFile = del.genes, gisticScoresFile = scores.gis, isTCGA = TRUE)
BLCA01laml.gistic@cnv.summary
BLCA01laml.gistic@gene.summary
and saw these results:
![image](https://user-images.githubusercontent.com/55881098/97144800-0f125d00-17a0-11eb-8c28-db9c55b64e8b.png)
![image](https://user-images.githubusercontent.com/55881098/97144816-16396b00-17a0-11eb-9931-8e09c5451eae.png)
It confused me. What did the column "Amp" "Del" "total" refer to? The times of copy number variation of the gene or sample? Thank you for your answer!
