### ISSUE TITLE
Issue in rainfall plot

### ISSUE THREAD

**Issue by raman91** [PoisonAlien/maftools#65]
Hi,
I am running maftools for creating rainfall plots with detectChangePoints set to TRUE. However, i am not able to get Start_Position, End_Position, nMuts, Avg_intermutation_dist, Size, number of C>A, C>T, T>C, C>G, T>A, T>G changes in my result. I am only able to get the chromosome and position in my result. Is there any way that i can get those details in my result? Thanks
Regards
Raman

**Comment by PoisonAlien** [comment]
Hi Raman,
This feature is only available on Github version of maftools for now. Maybe you can install it from github and try. 

```r
library("devtools")
install_github(repo = "PoisonAlien/maftools")
```

Let me know if you find any issues.

**Comment by raman91** [comment]
I have installed using the github version of maftools. But i am getting the output mentioning the chromosome and position only
Thanks

**Comment by raman91** [comment]
Thanks a lot

**Comment by raman91** [comment]
Thank you, it worked.
May i know how to change the colour of the rainfall plot. I am having issues with it. 
Thanks

**Comment by PoisonAlien** [comment]
Hi,
you need to define a color scheme (a names vector) for each Transition and
Transversion classification and pass it to col argument of plotTiTv .


col = c('coral4', 'lightcyan4', 'cornflowerblue', 'lightsalmon1', '
forestgreen', 'deeppink3') names(col) = c('C>T', 'C>G', 'C>A', 'T>A', 'T>C',
'T>G')

**Comment by raman91** [comment]
Thank you :)

**Comment by raman91** [comment]
For some of my samples, i am getting an error:
Error in multiple.mean.norm(data, mul.method = method, penalty, pen.value,  : 
  Minimum segment legnth is too large to include a change in this data

What does it mean?

Thanks 

Regards
Raman

**Comment by PoisonAlien** [comment]
I am guessing you're working on Kataegis? Anyways, original method describing identification of such genomic loci used PCF method

**********************************
*For each sample, all mutations were ordered by chromosomal position and the intermutation distance, defined as the number of base pairs from each mutation to the next one, was calculated. Intermutation distances were then segmented using the piecewise constant fitting (PCF) method63 to find regions of constant intermutation distance. Parameters used for PCF were γ = 25 and kmin = 2 and were trained on the set of kataegis foci that had been manually identified, curated and validated using orthogonal sequencing platforms6. Putative regions of kataegis were identified as those segments containing six or more consecutive mutations with an average intermutation distance of less than or equal to 1,000 bp.*
**********************************

But the method being used in maftools uses `changepoint` detection method. I have used this method on  published [results](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4972030/) to to see if it matches and it seems to work well. However, it is bit sensitive i.e, it does include few false positives and larger segments with high inter-mutation distance. The error that you're seeing is due to this issue, it is identifying larger segments; I am still working on it. Maybe over the next few weeks it should be fixed. 

Till then be-careful with the regions identified, you may have to further filter them based on inter mutation distance.

**Comment by raman91** [comment]
Ok, thanks a lot :)
