### ISSUE TITLE
Error for including "clinicalData", and the content and roles of "Tumor_Sample_Barcode" column in the .maf file

### ISSUE THREAD

**Issue by zzygyx9119** [PoisonAlien/maftools#66]
Dear PoisonAlien,

I am sorry to bother you. I was trying to follow through the samples to learn how to use maftools because it is the exact tool I need. Thanks for developing this useful tool.

when I use "laml = read.maf(maf = laml.maf, clinicalData = laml.clin)", I got the an error like this:

_Error in read.maf(maf = laml.maf, clinicalData = laml.clin) : 
  unused argument (clinicalData = laml.clin)_

In addition, I was wondering whether the column "Tumor_Sample_Barcode" in the .maf file must use the format like this "TCGA-05-4249-01A-01D-1105-08", or something else such as a normal sample name like "FF_1, FF_2 ,....".  What information will the maftools extract from the sample's barcode? 

I would greatly appreciate your kind help.

Jeff

**Comment by PoisonAlien** [comment]
Hi Jeff,
`Tumor_Sample_Barcode` can be of any format, it doesn't matter. 
If your data is from TCGA and is you set `isTCGA = TRUE`, it will use first 12 characters instead of whole string. i.e, TCGA-05-4249-01A-01D-1105-08 -> TCGA-05-4249

For your first question, I guess you installed maftools from Bioconductor, could you try installing from GitHub source and try again. It's still not updated on Bioconductor release branch. 

Let me know if you have issues.

**Comment by zzygyx9119** [comment]
Dear PoisonAlien,

Thanks a lot for your great help! 

Jeff
