### ISSUE TITLE
Sample size discrepancy

### ISSUE THREAD

**Issue by Anahit19** [PoisonAlien/maftools#727]
**Describe the issue**

Hi. I am using maftools for my file generated from vcftomaf. In my original vcf file I had 36 samples but when I open it with maftools it shows only one sample.

**Command**
I am trying to open my file with 

Arm = read.maf(maf ='chr22.test.vep.maf')

```r
```

**Session info**
> Arm
An object of class  MAF 
                        ID summary Mean Median
 1:             NCBI_Build  GRCh38   NA     NA
 2:                 Center       .   NA     NA
 3:                Samples       1   NA     NA
 4:                 nGenes     340   NA     NA
 5:        Frame_Shift_Del      21   21     21
 6:        Frame_Shift_Ins       7    7      7
 7:           In_Frame_Del      19   19     19
 8:           In_Frame_Ins      15   15     15
 9:      Missense_Mutation    1039 1039   1039
10:      Nonsense_Mutation      15   15     15
11:       Nonstop_Mutation       1    1      1
12:            Splice_Site      27   27     27
13: Translation_Start_Site       2    2      2
14:                  total    1146 1146   1146

```r
```
What could be the issue? Thank you very much

**Comment by PoisonAlien** [comment]
Hi,

It is quite difficult to suggest a solution without a reproducible example. But my guess is that, your original VCF is a merged VCF containing all the 36 samples? In that case I think `vcf2maf` will only generate one MAF (you can double check this). Possible solution is to split the vcf with [vcf-subset](https://vcftools.github.io/perl_module.html#vcf-subset) into one file per sample and run `vcf2maf` on them. You can then run `merge_mafs` from maftools on the resulting MAFs .  Hope this helps..

**Comment by Anahit19** [comment]
Thank you very much for your prompt reply! I will rerun the analyses now.

Just a quick additional question- is there is a way to analyse indel length distribution in maftools?

**Comment by PoisonAlien** [comment]
Unfortunately there is no direct way to do this. But with bit of workaround you can get the size of INDELS

Here is an example 
```r
laml.maf = system.file("extdata", "tcga_laml.maf.gz", package = "maftools") #MAF file
laml.clin = system.file('extdata', 'tcga_laml_annot.tsv', package = 'maftools') #clinical data
laml = read.maf(maf = laml.maf, clinicalData = laml.clin)

# fetch all INDELS
indels = subsetMaf(maf = laml, genes = c('DNMT3A', 'NPM1'),
          query = "Variant_Type %in% c('INS', 'DEL')", mafObj = FALSE)

# get the size
indel_lens = nchar(indels$Tumor_Seq_Allele2) - nchar(indels$Reference_Allele)

indel_lens
[[1] 0 0 0 0 6 0 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3

# OR if you would like absoulte length of INDELS
indel_lens = nchar(indels$Tumor_Seq_Allele2)

hist(indel_lens)
```

**Comment by Anahit19** [comment]
Thank you for your kind help!

If I may ask my last question :)

I am constructing now my oncoplots with maftools.

I got this warning message:

> plotmafSummary(maf = laml, rmOutlier = TRUE, addStat = 'median', dashboard = TRUE, titvRaw = FALSE)
Warning message:
In titv(maf = maf, useSyn = TRUE, plot = FALSE) :
  Non standard Ti/Tv class: 34099TRUE

> oncoplot(maf = laml, top = 10)
Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf

And the output plot looks a bit strange for me. Do you think the problem is how my maf file was generated?
![oncoplot](https://user-images.githubusercontent.com/53218207/121009016-b29b0580-c7a4-11eb-9db7-b62d8e7a65aa.jpeg)

**Comment by Anahit19** [comment]
But the summary plot seems that looks ok.

**Comment by PoisonAlien** [comment]
After the variant annotation, it is a critical step to remove SNPs that are found in public databases such as `dbSNP`, `ExAC`, `GnomAD`, etc. In your case I dont think you have done such things hence you get lots of hits for the same gene (`Multi_Hit`).

You will prolly have to read individual MAF file into R or you can do it in Python line by line, and remove such SNPs before doing any actual analysis. Something filtering to consider (just for starters).. 

SNP filter
  * ExAC_nontcga_ALL < 0.01 (1%) (SNP filter)
  * gnomAD_genome_ALL < 0.01 (1%) (SNP filter)

Other false positive filters (up to you if you want to remove.. )
  * tumor depth > 14 with alt counts supported by >4 reads (quality fiter)
  * reference depth > 8 with alt counts supported by < 1 and vaf < 0.01 (quality fiter)
  * FILTER == PASS (quality filter)


You MAF files from VEP should contain similar columns for ExAC, gnomAD, dbSNP. Under these column, it should have the minor allele frequencies. General threshold is `0.01`, i.e, the variant is found in > 1% of the population which makes it as a SNP rather than disease causing variant. You will have to remove them.. 

I had a script for filtering VEP output, but I can not seem to find it unfortunately. I also suggest to read more about variant filtering..

**Comment by Anahit19** [comment]
Thank you very much for your very detailed help!

**Comment by Anahit19** [comment]
Can I please ask a further question on the plot generated from plotmafSummary, as I think there might be an issue with it (attached). This plot refers to chromosome 1 for 36 individuals (these are not cancer patients, just a random sample from the population). The first two plots (Variant Classification and Variant Type) refer to ~300k variants. But the third plot (SNV class) refers to over 3M variants. Looking at the same plots on the vignette, I would expect them to all be referring to the same number of variants. Any idea of what might have generated such a discrepancy? Thank you!
[Rplots.pdf](https://github.com/PoisonAlien/maftools/files/6776368/Rplots.pdf)

**Comment by PoisonAlien** [comment]
Hi,
Transitions and Transversions are estimated using both synonymous and non-synonymous variants. So, the counts represents the whole landscape.

**Comment by Anahit19** [comment]
Thank you!
