### ISSUE TITLE
somaticInteractions errors if most variants present in all samples

### ISSUE THREAD

**Issue by geejaytee** [PoisonAlien/maftools#921]
Plotting the somaticInteractions when variants are present in all samples either returns an error:

In the following example, HERC2, POLE, POLD1 and NUP93 are present in all seven samples of my maf file:

<img width="375" alt="Screenshot 2023-03-31 at 11 50 50" src="https://user-images.githubusercontent.com/27360278/229101117-5259de23-13fe-40d8-a8cb-75bae7c713aa.png">

(I'm assuming this is intentional, as they all co-occur in all samples, so there is no meaningful fisher test that can be done for these)

Restricting to a small number of genes outside those four gives an error when running somaticInteractions:

```
> somaticInteractions(
+ maf = laml,
+ top = 8,
+ showSum = TRUE,
+ pvalue = c(0.05, 0.01),
+ fontSize = 0.5,
+ countType = "all",
+ countsFontSize = 0.1
+ )
Error in eval(jsub, SDenv, parent.frame()) : object '01' not found
```
when there should be interactions between genes 5-8 even if no meaningful interactions found between genes 1-4. Running it with the top 9 genes does not generate an error like this.

Could the function be improved to add an option to remove those which are present in all samples?

**Comment by PoisonAlien** [comment]
Hi,

Would it be possible to share a reproducible example? You can remove any sensitive information and retain only necessary columns.

**Comment by geejaytee** [comment]
Can I email it over? I can provide more detail this way.

**Comment by PoisonAlien** [comment]
Sure, This is my email: anandmt3@gmail.com

**Comment by PoisonAlien** [comment]
Hello Graeme, 

Sorry for the late reply. I was trying out different methods on how to handle this situation. It occurs primarily when the sample size is small. The blank spaces in the plot are due to `NA`s being generated when fisher test could not be performed  for two obvious reasons. 

1. When all the samples are mutated in the same direction. For example as in the below figure - HERC2 and NUP93 are mutated in all the samples in co-occuring manner. In this case a fisher test can not be calculated because we won't be able to create a 2x2 contingency table.

Here is a sample demo (1 = mutated, 0 = wt).

![Screenshot 2023-04-03 at 16 46 58](https://user-images.githubusercontent.com/8164062/229545316-fc942141-41ca-4b25-9a30-5a4b3fc521cb.png)

```r
herc2_mutats = c(1, 1, 1, 1, 1, 1, 1)
nup93_mutats = c(1, 1, 1, 1, 1, 1, 1)

#make a contingency table 
ctbl = table(herc2_mutats, nup93_mutats)

ctbl
            nup93_mutats
herc2_mutats 1
           1 7

fisher.test(x = ctbl)
Error in fisher.test(x = ctbl) : 
  'x' must have at least 2 rows and columns
```



2. In the second situation, one of the gene lacks `wt` or simply put has all the samples in one direction (wt or mutated). In this case as well, we won't be able to create a 2x2 continence table. 

Here is a sample demo (1 = mutated, 0 = wt).

![Screenshot 2023-04-03 at 16 45 08](https://user-images.githubusercontent.com/8164062/229544863-93440822-d605-4752-8acc-383951d7552c.png)

```r
pold1_mutats = c(1, 1, 1, 1, 1, 1, 1)
bap1_mutats = c(1, 1, 1, 1, 0, 0, 0)

#make a contingency table 
ctbl = table(pold1_mutats, bap1_mutats)

ctbl
            bap1_mutats
pold1_mutats 0 1
           1 3 4

fisher.test(ctbl)
Error in fisher.test(ctbl) : 'x' must have at least 2 rows and columns
```

There are several alternative approaches to estimate exclusive or co-occuring events which will account for scenarios like these. But for now, there is not much we can do about Fishers test. With that in mind, I will push some changes that will emit warnings when the above situations are encountered. 

Thanks for the issue.

**Comment by geejaytee** [comment]
Thanks, will the update alter the behaviour for small numbers of genes? The function as it stands throws an error for 5-8 genes (with my example) with 4 present in all samples, but not for n>9
