### ISSUE TITLE
A question about tmb()

### ISSUE THREAD

**Issue by YoungCCCCCCC** [PoisonAlien/maftools#972]
Hi!

I'm using tmb() to calculate the TMB value of my WXS samples which were downloaded from GDC. I realaized the default value of 'captureSize' is 50Mb.  I'm not sure about if this value is suitable or not for WXS data, because I find some people and studies use 38Mb as the 'captureSize '. Unfortunately I didn't find any information about the size of WXS in official documents.

So can I ask that why that  default value is 50Mb? Does it mean the default size of WXS is so?

**Comment by PoisonAlien** [comment]
Hi,

This is because of [Agilent Sureselect V4 kit](https://www.agilent.com/cs/library/flyers/Public/5990-9857en_lo.pdf) which is the most commonly used kit in WXS. 

TCGA studies do not use any universal kit across the studies which makes it difficult to guess the target size. You could try [MC3 cohort](https://doi.org/10.1016/j.cels.2018.03.002) for estimating tmb.

**Comment by YoungCCCCCCC** [comment]
Thank you so much for your reply! I think my problem is solved.

Wish you have great day!
